apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "app.metadataLabels" $ | nindent 4 }}
  annotations:
    {{- include "app.metadataAnnotations" $ | nindent 4 }}
  name: {{ template "app.name" . }}-flask
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "app.metadataLabels" $ | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app.metadataLabels" $ | nindent 8 }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8000"
    spec:
      containers:
      - image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        name: flask
        livenessProbe:
          httpGet:
            path: /health/live
            port: 5000
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 5000
        env:
          - name: REDIS_HOST
            value: {{ template "app.name" . }}-redis-master
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "app.name" . }}-redis
                key: redis-password
        resources:
          requests:
            memory:  {{ .Values.resources.requests.memory }}
            cpu:  {{ .Values.resources.requests.cpu }}
          limits:
            memory:  {{ .Values.resources.limits.memory }}
            cpu:  {{ .Values.resources.limits.cpu }}
            